### ISSUE TITLE
User/driver page should show more info about what they've done, and are doing

### ISSUE THREAD

**Issue by john** [collectiveidea/audited#474] opened 2018-11-07 01:28 UTC
And there appears to be a bug where it's not showing Conversations (which are proxies for Rides), even where they've provided rides.

It should show all rides they've given, conversations they've taken part in, etc.

**Comment by tbrisker** [comment] 2018-11-07 14:03
@john I this you commented on the wrong project, since we don't have anything related to any of what you've written about. closing, if i'm mistaken please explain how the issue is related to the audited gem.

**Closed by tbrisker** 2018-11-07 14:03 UTC
