### ISSUE TITLE
Selecting maximum version number is slow with large audits table

### ISSUE THREAD

**Issue by aripollak** [collectiveidea/audited#189] opened 2014-09-05 01:40 UTC
We're using PostgreSQL with a fairly large (millions of records) audits table, and updating a record with thousands of audits often takes more than 15 seconds due to the [maximum version number select](https://github.com/collectiveidea/audited/blob/cd7065ef6fb9640a3a4e204477dd38dc0d12e50c/lib/audited/adapters/active_record/audit.rb#L61) code. Is there a particular use case for updating the version number like that? Given that there are already id and created_at columns, I'm not sure why an extra version column is needed.

Looks like this was reported a while ago at #103, but that was closed for some reason.

**Comment by kennethkalmer** [comment] 2015-02-13 07:51
@aripollak either I don't remember, or I don't know why `maximum(:version)` is used. Most probably it was just naive and nobody thought records with that many changes would be audited. That said, here we are and I'm not knowledgeable (yet) to get this fixed properly.

How could we accurately measure the performance so we can make a proper fix for this?

I ask because I don't know where the bottleneck lies. Is it in sweeping the entire table looking for max? Are we missing indexes that could shorten the sweep? Is it because of the sheer number of audits associated to a single object, or can we just throw a million _version 1_ objects into a table and get the same?

I would like to get this resolved! So any tips on reproducing the issue would be great.

**Comment by aripollak** [comment] 2015-02-13 15:44
It definitely slows down in Postgres when there are lots of audit records for the same underlying record. 

```sql
# select count(id), auditable_id, auditable_type from audits group by auditable_id, auditable_type order by count(*) desc limit 1;
 count | auditable_id | auditable_type 
-------+--------------+----------------
 37729 |        99160 | User

# explain analyze select max(version) from audits where auditable_id=99160 and auditable_type='User';
Aggregate  (cost=30333.99..30333.99 rows=1 width=4) (actual time=58624.490..58624.490 rows=1 loops=1)
  ->  Bitmap Heap Scan on audits  (cost=450.82..30316.74 rows=34505 width=4) (actual time=239.481..58609.304 rows=37735 loops=1)
        Recheck Cond: ((auditable_id = 99160) AND ((auditable_type)::text = 'User'::text))
        ->  Bitmap Index Scan on auditable_index  (cost=0.00..449.10 rows=34505 width=0) (actual time=230.132..230.132 rows=37736 loops=1)
              Index Cond: ((auditable_id = 99160) AND ((auditable_type)::text = 'User'::text))
Total runtime: 58624.652 ms

# explain analyze select max(version) from audits where auditable_id=1 and auditable_type='User';
 Aggregate  (cost=291.21..291.22 rows=1 width=4) (actual time=157.793..157.793 rows=1 loops=1)
   ->  Index Scan using auditable_index on audits  (cost=0.09..291.12 rows=195 width=4) (actual time=0.076..157.652 rows=226 loops=1)
         Index Cond: ((auditable_id = 1) AND ((auditable_type)::text = 'User'::text))
 Total runtime: 157.833 ms

```

Note that these were run on an active production database where that query had not been cached. Subsequent queries are faster, as was running it locally, but the query plan stayed the same.

We ended up monkey-patching `set_version_number` to always return nil, but we haven't needed to use any of the methods that use the version. Given that most modern databases offer sub-second timestamp precision, keeping the extra version seems redundant, even if an index on it would speed things up a bit (I'm not sure it would on most databases)

**Comment by lucianosousa** [comment] 2016-03-23 14:36
:+1: for this issue. one insert in my table took 45s.

**Comment by lucianosousa** [comment] 2016-03-23 19:35
I'm not a DB expert and hope that what I'm doing here can be a solution for the gem.

What I did was create an `index` for `version` field.
My insert now works like a charm, but I don't know if this is the correct approach.

Do you guys have some thought?

**Closed** 2018-04-04 13:25 UTC

**Comment by aripollak** [comment] 2018-04-04 15:42
@tbrisker that fixes the performance issue, but why is the `version` field necessary at all?

**Comment by tbrisker** [comment] 2018-04-04 18:51
@aripollak - Adding the version to the index allows this and other queries that need the version to perform the query using the index instead of having to go over the table itself.

**Comment by aripollak** [comment] 2018-04-04 20:31
@tbrisker that's why the addition of `version` to the index is needed, but why is `version` needed at all?

**Comment by aardvarkk** [comment] 2018-08-02 20:28
Also wondering the same thing. I don't believe our code uses the `version` identifier at all, so I'd prefer to save all of the `SELECT MAX` queries happening on insert, since the versioning info is useless (to us) as far as I can tell. It would be nice to disable the versioning through some kind of config variable so it wasn't stored or queried.

**Comment by pjar** [comment] 2021-02-08 10:31
Digging this up, as in our project we came to similar thoughts. The `version` column seems redundant, unless I miss something, it replicates the `id` field that is auto-incremented.

**Comment by lucianosousa** [comment] 2021-02-15 19:44
there is a while I don't use this gem, but as far as I can remember when you are updating a row, it creates a copy of the last state for you, right?

In order to do that, it stores the version of the change (ie: how many times this row was copied, + user who created it, and so on)

[set_version_number](https://github.com/collectiveidea/audited/blob/7fd8334edf682ea994b6f84980ddd19303590071/lib/audited/audit.rb#L179)

is one of the [callbacks](https://github.com/collectiveidea/audited/blob/7fd8334edf682ea994b6f84980ddd19303590071/lib/audited/audit.rb#L45) for this operation, that generates the version number for you

So, you are not using the `version` field directly, but _audited_ is using for you every time you are creating a snapshot/revision of a row
